const data = {
  Officer: [
    {
      EmployeeName: "BELAL UDDIN AHMED CHOWDHURY",
      VesselName: "AKIJ OCEAN",
      RankId: 1,
      RankName: "Master",
      RankSerial: 1,
      DocumentTypeId: 4,
      DocumentType: "CDC",
      Date: "2029-03-09T00:00:00",
      RankGroupId: 1,
    },
    {
      EmployeeName: "BELAL UDDIN AHMED CHOWDHURY",
      VesselName: "AKIJ OCEAN",
      RankId: 1,
      RankName: "Master",
      RankSerial: 1,
      DocumentTypeId: 17,
      DocumentType: "Passport",
      Date: "2029-03-09T00:00:00",
      RankGroupId: 1,
    },
    {
      EmployeeName: "MD MUNIRUL ISLAM",
      VesselName: "AKIJ NOBLE",
      RankId: 1,
      RankName: "Master",
      RankSerial: 1,
      DocumentTypeId: 17,
      DocumentType: "Passport",
      Date: "2031-06-20T00:00:00",
      RankGroupId: 1,
    },
    {
      EmployeeName: "MD SALEH AHMED RANA",
      VesselName: "AKIJ NOOR",
      RankId: 1,
      RankName: "Master",
      RankSerial: 1,
      DocumentTypeId: 4,
      DocumentType: "CDC",
      Date: "2029-11-17T00:00:00",
      RankGroupId: 1,
    },
    {
      EmployeeName: "Muhammad Nazmul Ahsan",
      VesselName: "AKIJ STAR",
      RankId: 1,
      RankName: "Master",
      RankSerial: 1,
      DocumentTypeId: 17,
      DocumentType: "Passport",
      Date: "2029-03-10T00:00:00",
      RankGroupId: 1,
    },
  ],
  Crew: [
    {
      EmployeeName: "RASHU AHMED",
      VesselName: "Test Vessel - 1",
      RankId: 2,
      RankName: "Chief/Off",
      RankSerial: 2,
      DocumentTypeId: 1,
      DocumentType: "Advance Fire-fighting VI/3",
      Date: "2022-03-30T00:00:00",
      RankGroupId: 1,
    },
    {
      EmployeeName: "RASHU AHMED",
      VesselName: "Test Vessel - 1",
      RankId: 2,
      RankName: "Chief/Off",
      RankSerial: 2,
      DocumentTypeId: 17,
      DocumentType: "Passport",
      Date: "2022-03-23T00:00:00",
      RankGroupId: 1,
    },
    {
      EmployeeName: "Saiful Islam Raju ",
      VesselName: "Test Vessel - 1",
      RankId: 2,
      RankName: "Chief/Off",
      RankSerial: 2,
      DocumentTypeId: 25,
      DocumentType: "NID",
      Date: "2022-04-29T00:00:00",
      RankGroupId: 1,
    },
    {
      EmployeeName: "MD YUSUF FARUK",
      VesselName: "AKIJ NOBLE",
      RankId: 2,
      RankName: "Chief/Off",
      RankSerial: 2,
      DocumentTypeId: 17,
      DocumentType: "Passport",
      Date: "2025-01-04T00:00:00",
      RankGroupId: 1,
    },
    {
      EmployeeName: "ISLAM MD SHAHIDUL",
      VesselName: "AKIJ NOOR",
      RankId: 2,
      RankName: "Chief/Off",
      RankSerial: 2,
      DocumentTypeId: 4,
      DocumentType: "CDC",
      Date: "2031-08-17T00:00:00",
      RankGroupId: 1,
    },
    {
      EmployeeName: "ISLAM MD SHAHIDUL",
      VesselName: "AKIJ NOOR",
      RankId: 2,
      RankName: "Chief/Off",
      RankSerial: 2,
      DocumentTypeId: 17,
      DocumentType: "Passport",
      Date: "2031-08-17T00:00:00",
      RankGroupId: 1,
    },
    {
      EmployeeName: "Mahbub Al Morshed",
      VesselName: "AKIJ STAR",
      RankId: 2,
      RankName: "Chief/Off",
      RankSerial: 2,
      DocumentTypeId: 4,
      DocumentType: "CDC",
      Date: "2028-10-30T00:00:00",
      RankGroupId: 1,
    },
    {
      EmployeeName: "Mahbub Al Morshed",
      VesselName: "AKIJ STAR",
      RankId: 2,
      RankName: "Chief/Off",
      RankSerial: 2,
      DocumentTypeId: 17,
      DocumentType: "Passport",
      Date: "2028-10-30T00:00:00",
      RankGroupId: 1,
    },
  ],
  Headers: [
    { DocumentTypeId: 1, DocumentType: "Advance Fire-fighting VI/3" },
    { DocumentTypeId: 2, DocumentType: "Basic Fire Fight (VI/1-2)" },
    { DocumentTypeId: 4, DocumentType: "CDC" },
    { DocumentTypeId: 17, DocumentType: "Passport" },
    { DocumentTypeId: 25, DocumentType: "NID" },
  ],
};

const dataset = {
  heads: [],
  rows: [
    ["mahmud", "", "date", "", "", ""],
    ["mahmud", "", "date", "", "", ""],
  ],
};

const finalArr = [];

for (let i = 0; i < data?.Officer?.length; i++) {
  for (let j = 0; j < data?.Headers?.length; j++) {
    
  }
}

const format = JSON.parse(JSON.stringify(data));

console.log(format);
